name: 'Sensitive Codepaths Check'
description: "A GitHub action to check for changes in specified codepaths of a pull request"
author: 'James Wickett'

branding:
  icon: 'code'
  color: 'blue'

inputs:
  sensitive_codepaths_file:
    description: "The YAML file containing the list of sensitive codepaths"
    required: true
  env:
    description: 'GitHub Personal Access Token'
    required: true

runs:
  using: 'composite'
    steps:
    - run: echo "Using the Check Sensitive Codepaths action"
      shell: bash